# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  labels:
  - "dependencies/ci"
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "weekly"
  labels:
  - "dependencies/python"
- package-ecosystem: "docker"
  directory: "/tests/azure-openai"
  schedule:
    interval: "weekly"
  labels:
  - "dependencies/docker"
