# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  labels:
  - "deps/ci"
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "monthly"
  labels:
  - "deps/python"
- package-ecosystem: "docker"
  directory: "/tests/ubuntu-22"
  schedule:
    interval: "monthly"
  labels:
  - "deps/docker"
- package-ecosystem: "docker"
  directory: "/tests/fedora-40"
  schedule:
    interval: "monthly"
  labels:
  - "deps/docker"
- package-ecosystem: "docker"
  directory: "/tests/archlinux-base"
  schedule:
    interval: "monthly"
  labels:
  - "deps/docker"
