name: Python tests
on:
  pull_request:
  push:
    branches:
    - main
jobs:
  python-tests:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
    - name: Install requirements
      run: |
        pip install -r .devcontainer/requirements-dev.txt
    - name: Run tests
      run: |
        coverage run --branch --include="src/fish_ai/*.py" -m pytest
        coverage xml
        coverage report
    - name: Report code coverage
      uses: orgoro/coverage@v3.2
      with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
