name: Python tests
on:
  pull_request:
  push:
    branches:
    - main
jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
    - name: Install requirements
      run: |
        pip install -r .devcontainer/requirements-dev.txt
    - name: Run tests
      run: |
        pytest
